DIAS_OMONTE/urls.py
from django.contrib import admin
from django.urls import path, include
from DIAS_OMONTE import views

urlpatterns = [
    path('', views.home, name='home'),
    path('restaurants/', include('RESTAURANTS.urls')),
    path('software-library/', include('SOFTWARE_LIBRARY.urls')),
    path('config/', admin.site.urls),
]

RESTAURANTS/urls.py
from django.urls.conf import path
from RESTAURANTS import views


app_name = 'RESTAURANTS'
urlpatterns = [
    path('', views.restaurants, name='restaurants'),
    path('details/<str:resto_name>/', views.details, name='details'),
]

SOFTWARE_LIBRARY/urls.py
from django.urls.conf import path
from SOFTWARE_LIBRARY import views


app_name = 'SOFTWARE_LIBRARY'
urlpatterns = [
    path('', views.softwareLibrary, name='software-library'),
    path('details/<str:software_name>/', views.softwareDetails, name='details'),
    path('search/', views.search, name='search'),
    
]

RESTAURANTS/models.py
from DIAS_OMONTE.settings import STATICFILES_DIRS
from django.db import models

class CodePostal(models.Model):
    codePostal_name = models.PositiveIntegerField('Code Postal', blank=False, primary_key=True)

    def __str__(self):
        return str(self.codePostal_name)

    class Meta:
        verbose_name = 'Code Postal'
        verbose_name_plural = 'Code Postaux'


class Villes(models.Model):
    ville_name = models.CharField('Ville', max_length=100, blank=False, primary_key=True)
    cp_name = models.ForeignKey(CodePostal, on_delete=models.PROTECT)

    def __str__(self):
        return self.ville_name

    class Meta:
        verbose_name = 'Ville'
        verbose_name_plural = 'Villes'


class Pays(models.Model):
    pays_name = models.CharField('Pays', max_length=100, blank=False, primary_key=True)
    
    def __str__(self):
        return str(self.pays_name)

    class Meta:
        verbose_name = 'Pays'
        verbose_name_plural = 'Pays'


class Restaurant(models.Model):
    restaurant_name = models.CharField('Nom du restaurant', max_length=100, blank=False, primary_key=True)
    email = models.EmailField('Email', max_length=150, blank=True, editable=True)
    country = models.ForeignKey(Pays, on_delete=models.PROTECT)
    adress = models.CharField('Adresse du restaurant', max_length=200, blank=False)
    city = models.ForeignKey(Villes, on_delete=models.PROTECT)
    phone = models.CharField('Numéro de téléphone', unique=True, blank=True, max_length=20, editable=True)
    webSite = models.URLField('Site web', blank=True, editable=True)
    image = models.URLField('Lien de l\'image', blank=False)

    def __str__(self):
        return self.restaurant_name

    class Meta:
        verbose_name = 'Restaurant'
        verbose_name_plural = 'Restaurants'

SOFTWARE_LIBRARY/models.py
from django.db import models

class Category(models.Model):
    category_name = models.CharField('Catégorie du Logiciel', max_length=30, blank=False, primary_key=True)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = 'Catégorie'
        verbose_name_plural = 'Catégories'


class License(models.Model):
    license_name = models.CharField('Licence', max_length=100, blank=False, primary_key=True)

    def __str__(self):
        return self.license_name

    class Meta:
        verbose_name = 'Licence'
        verbose_name_plural = 'Licences'


class Developer(models.Model):
    developer_name = models.CharField('Auteur du Logiciel', max_length=50, blank=False, primary_key=True)
    developer_web_site = models.URLField('Site web du créateur du Logiciel', max_length=200, blank=True)

    def __str__(self):
        return self.developer_name

    class Meta:
        verbose_name = 'Developpeur'
        verbose_name_plural = 'Developpeurs'


class Software(models.Model):
    software_name = models.CharField('Nom du Logiciel', max_length=100, blank=False, primary_key=True)
    software_logo = models.URLField('Logo du Logiciel', max_length=200, blank=False)
    software_description = models.TextField('Description', blank=True)
    software_image = models.URLField('Image du Logiciel', max_length=200, blank=False)
    software_version = models.CharField('Version du Logiciel', max_length=20, blank=True)
    software_category = models.ForeignKey(Category, on_delete=models.PROTECT)
    software_license = models.ForeignKey(License, on_delete=models.PROTECT)
    software_developer = models.ForeignKey(Developer, on_delete=models.PROTECT)
    software_source = models.URLField('Source du Logiciel', max_length=200, blank=False)
    software_download_size = models.CharField('Taille du fichier téléchargé', max_length=15, blank=True)

    def __str__(self):
        return self.software_name
    
    class Meta:
        verbose_name = 'Logiciel'
        verbose_name_plural = 'Logiciels'

DIAS_OMONTE/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'DIAS_OMONTE/home.html')

RESTAURANTS/views.py
from RESTAURANTS.models import Restaurant
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator

def restaurants(request):
    restos = Restaurant.objects.order_by('restaurant_name')
    paginator = Paginator(restos, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'RESTAURANTS/restaurants.html', context)

def details(request, resto_name):
    resto = get_object_or_404(Restaurant, pk=resto_name)
    context = {'resto': resto}
    return render(request, 'RESTAURANTS/restaurants-details.html', context)

SOFTWARE_LIBRARY/views.py
from django.core.paginator import Paginator
from SOFTWARE_LIBRARY.models import Category, Software
from django.shortcuts import get_object_or_404, render

def softwareLibrary(request):
    softwares = Software.objects.all().order_by('software_name')
    categories = Category.objects.all()
    paginator = Paginator(softwares, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'software': softwares,
        'page_obj': page_obj,
        'categories': categories,
        'page_number':page_number
    }
    return render(request, 'SOFTWARE_LIBRARY/software-library.html', context)

def softwareDetails(request, software_name):
    software = get_object_or_404(Software, pk=software_name)
    software_description_char_count = len(software.software_description)
    logiciels = Software.objects.all().order_by('software_name')
    paginator = Paginator(logiciels, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'software_details': software,
        'page_number': page_number,
        'page_obj': page_obj,
        'software_description_char_count': software_description_char_count
    }
    return render(request, 'SOFTWARE_LIBRARY/software-details.html', context)

def search(request):
    categories = Category.objects.all().order_by('category_name')
    query = request.GET.get('query')
    if not query:
        software = Software.objects.all().order_by('software_name')
    else:
        # title contains the query is and query is not sensitive to case.
        software = Software.objects.filter(software_name__icontains=query).order_by('software_name')
    if not software.exists():
        software = Software.objects.filter(software_category__category_name__icontains=query).order_by('software_name')
    if not software.exists():
        software = Software.objects.filter(software_developer__developer_name__icontains=query).order_by('software_name')
    if not software.exists():
        software = Software.objects.filter(software_license__license_name__icontains=query).order_by('software_name')
    results = "Résultats pour la requête : %s" % query

    paginator = Paginator(software, 15)
    page_number = request.GET.get('page')
    page_obj_search = paginator.get_page(page_number)
    context = {
        'page_obj_search': page_obj_search,
        'results': results,
        'categories': categories,
        'page_number': page_number,
        'query': query,
    }
    return render(request, 'SOFTWARE_LIBRARY/software-library-search.html', context)


def category(request, category_name):
    categories = Category.objects.all()
    all_software = Software.objects.all().order_by('software_name')
    software_categories = Software.objects.none()
    for software in all_software:
        if software.software_category.category_name == category_name:
            software_categories = Software.objects.filter(software_category__category_name=category_name)
    context = {
        'categories': categories,
        'software_categories': software_categories,
        'categoryName': category_name,
    }
    return render(request, 'SOFTWARE_LIBRARY/software-library-categories.html', context)

RESTAURANTS/templates/RESTAURANTS/restaurants-details.html
{% extends 'layout/head.html' %}
{% load static %}
{% block title %}DETAILS{% endblock title %}
{% block favicon %}<link rel="shortcut icon" type="image/png" href="{{ resto.image }}">{% endblock favicon %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
			<li class="breadcrumb-item"><a class = "btn lien" href="{% url 'home' %}"><img src="{% static 'medias/images/photo_alexandre.png' %}" alt="photo alexandre" width=21 height=24/></a></li>
            <li class="breadcrumb-item"><a class="btn lien" href="{% url 'RESTAURANTS:restaurants' %}">RESTAURANTS</a></li>
            <li class="breadcrumb-item active"><a class="btn lien">{{ resto.restaurant_name }}</a></li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block body %}
	<h2 class="text-center">{{ resto.restaurant_name | upper }}</h2>
	<div class="clearfix" style="margin-top:2%">
		<img class="resto-img col-md-6 float-md-start mb-4 ms-md-4" style="margin-right:4%" src="{{ resto.image }}" width=50% height=50%>
		<h4>{{ resto.adress }} {{ resto.city.cp_name }} {{ resto.city }}, {{ resto.country }}</h4>
		<h4><i class="bi bi-telephone-fill"></i>&nbsp;<a href="tel:{{ resto.phone }}">{{ resto.phone }}</a></h4>
		<h4><i class="bi bi-envelope-fill"></i>&nbsp;<a href="mailto:{{ resto.email }}">{{ resto.email }}</a></h4>
		<h4><i class="bi bi-globe"></i></i>&nbsp;<a href="{{ resto.webSite }}" target="_blank">{{ resto.webSite }}</a></h4>
	</div>
{% endblock body %}

RESTAURANTS/templates/RESTAURANTS/restaurants.html
{% extends 'layout/head.html' %}
{% load static %}
{% block title %}RESTAURANTS{% endblock title %}
{% block favicon %}<link rel="shortcut icon" type="image/png" href="{% static 'medias/images/logo-restaurant-fond-1.png' %}">{% endblock favicon %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="btn lien" href="{% url 'home' %}"><img src="{% static 'medias/images/photo_alexandre.png' %}" alt="photo alexandre" width=21 height=24/></a></li>
            <li class="breadcrumb-item active"><a class="btn lien">Restaurants</a></li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block body %}
    {% include 'layout/pagination.html' %}
    <div class="row row-cols-1 row-cols-md-3" style="margin: 15px 10px 15px 15px;">
        {% for resto in page_obj %}
            <a style="margin-bottom: 10px;" href="details/{{resto.restaurant_name}}?page={% if page_number == None %}1{% else %}{{ page_number }}{% endif %}">
                <button class="card w-100 h-100 button-software" style="background-color: #A9EAFE;border:none">
                    <h2>{{ resto.restaurant_name | upper }}</h2>
                    <img class="resto-image" style="padding:0px;" width="100%" height="100%" src="{{ resto.image }}" alt="{{ resto.restaurant_name }}">
                    <h4 style="margin-top:5%">{{ resto.city }}, {{ resto.country }}</h4>
                </button>
            </a>
        {% endfor %}
    </div>
    {% include 'layout/pagination.html' %}
{% endblock body %}

SOFTWARE_LIBRARY/templates/SOFTWARE_LIBRARY/software-details.html
{% extends 'layout/head.html' %}
{% load static %}
{% block title %}SOFTWARE - {{ software_details.software_name }}{% endblock title %}
{% block favicon %}<link rel="shortcut icon" type="image/png" href="{{ software_details.software_logo }}">{% endblock favicon%}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="btn lien" href="{% url 'home' %}"><img src="{% static 'medias/images/photo_alexandre.png' %}" width=21 height=24 /></a></li>
			<li class="breadcrumb-item active"><a class="btn lien"  href="{% url 'SOFTWARE_LIBRARY:software-library' %}?page={{ page_number }}">SOFTWARE LIIBRARY</a></li>
			<li class="breadcrumb-item active"><a class="btn lien">{{ software_details.software_name }}</a></li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block body %}
	<nav class="navbar navbar-expand-lg navbar-expand-md navbar-expand-sm navbar-light" style="background-color: #74D0F1">
		<div class="container-fluid">
			<span class="navbar-brand">
				<a class="btn lien" href="{% url 'SOFTWARE_LIBRARY:software-library' %}?page={{ page_number }}">
					<i class="fas fa-chevron-left fa-3x lien"></i><img src="{{ software_details.software_logo }}" alt="{{ software_details.software_name }}" width="50px" height="50px"/>
					<span class="btn lien">{{ software_details.software_name }}</span>
				</a>
			</span>
			<span class="col col-4">
				<label class="btn-lg h4">Version: {{ software_details.software_version }}</label>
				<a class="btn btn-lg btn-success" href="{{ software_details.software_source }}" download="{{ software_details.software_source }}" target="_blank">
					<span class="h4">Install</span>
				</a>
			</span>
		</div>
	</nav>
	<div class="col col-12 col-lg-12 col-md-12 col-sm-12" style="text-align: center;padding-top: 30px;padding-bottom: 30px;background-color: #EFEFEF">
		<img src="{{ software_details.software_image }}" alt="{{ software_details.software_name }}" width="50%" height="50%"/>
	</div>
	<div class="h5 row row-cols-12 col col-12 col-lg-12 col-md-12 col-sm-12" style="background-color: #FFFFFF;margin: 0px;padding-top:2%">
		<div class="col-6">
			<span class="h4 fw-bold">Description :</span>
			<div style="padding-left: 30px;padding-top: 10px;padding-bottom: 3%;">
				{% if software_description_char_count <= 200 %}
					<textarea rows="3" cols="60">{{ software_details.software_description }}</textarea>
				{% elif software_description_char_count > 200 and software_description_char_count <= 400 %}
					<textarea rows="6" cols="60">{{ software_details.software_description }}</textarea>
				{% elif software_description_char_count > 400 and software_description_char_count <= 600 %}
					<textarea rows="9" cols="60">{{ software_details.software_description }}</textarea>
				{% endif %}
			</div>
		</div>
		<div class="offset-1 col-4">
			<div class="h4 fw-bold">
				LICENSE : <span class="fw-normal h5">{{ software_details.software_license }}</span>
			</div>
			<div class="h4 fw-bold">
				Developer : <span class="fw-normal h5">{{ software_details.software_developer.developer_name }}</span>
			</div>
			<div style="padding-top: 10px">
				<a href="{{ software_details.software_developer.developer_web_site }}" target="_blank">{{ software_details.software_developer.developer_web_site }}</a>
			</div>
		</div>
	</div>
{% endblock body %}

SOFTWARE_LIBRARY/templates/SOFTWARE_LIBRARY/software-library-search.html
{% extends 'layout/head.html' %}
{% load static %}
{% block title %}Search{% endblock title %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="btn lien" href="{% url 'home' %}"><img src="{% static 'medias/images/photo_alexandre.png' %}" width=21 height=24 /></a></li>
			<li class="breadcrumb-item active"><a class="btn lien" href="{% url 'SOFTWARE_LIBRARY:software-library' %}?page={{ page_number }}">SOFTWARE LIIBRARY</a></li>
			<li class="breadcrumb-item active"><a class="btn lien">R&Eacute;SULTAT POUR <mark style="background-color: #74D0F1;padding: 10px;"><b>{{ query }}</mark></b></a></li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block body %}
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container-fluid">
			{% include 'SOFTWARE_LIBRARY/software_search_form.html' %}
			<ul class="nav nav-pills">
				<li class="nav-item">
					<a class="nav-link" style="padding: 10px 15px;border-radius: 0" aria-current="page" href="{% url 'SOFTWARE_LIBRARY:software-library' %}">
						All
					</a>
				</li>
				{% for category in categories %}
					<li class="nav-item">
						<a class="nav-link" style="padding: 10px 15px;border-radius: 0" aria-current="page" href="/software-library/{{ category.category_name }}">
							{{ category }}
						</a>
					</li>
				{% endfor %}
			</ul>
		</div>
	</nav>
	{% include 'layout/pagination_search.html' %}
	<div class="row row-cols-1 row-cols-md-4" style="margin: 15px 10px 15px 15px;">
		{% for software_search in page_obj_search %}
			<a style="margin-bottom: 20px" href="/software-library/details/{{ software_search.software_name }}?page={% if page_number == None %}1{% else %}{{ page_number }}{% endif %}">
				<button class="card w-100 h-100 button-software">
					<img class="logo-image" style="width: 128px;height: 128px" src="{{ software_search.software_logo }}" alt="{{ software_search.software_name }}"/>
					<div class="card-body">
						<h5 class="text-uppercase text-center">{{ software_search.software_name }}</h5>
					</div>
				</button>
			</a>
		{% endfor %}
	</div>
	{% include 'layout/pagination_search.html' %}
{% endblock body %}

SOFTWARE_LIBRARY/templates/SOFTWARE_LIBRARY/software-library.html
{% extends 'layout/head.html' %}
{% load static %}
{% block title %}SOFTWARE LIBRARY{% endblock title %}
{% block favicon %}<link rel="shortcut icon" type="image/png" href="{% static 'medias/images/favicon-software-library.png' %}">{% endblock favicon %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="btn lien" href="{% url 'home' %}"><img src="{% static 'medias/images/photo_alexandre.png' %}" width=21 height=24 /></a></li>
			<li class="breadcrumb-item active"><a class="btn lien">SOFTWARE LIIBRARY</a></li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block body %}
	<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:10px;">
		<div class="container-fluid">
			<ul class="nav nav-pills">
				{% if category_name == None %}
					<li class="nav-item">
						<a class="nav-link active" style="padding: 10px 15px;border-radius: 0" aria-current="page" href="{% url 'SOFTWARE_LIBRARY:software-library' %}">
							All
						</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link lien" style="padding: 10px 15px;border-radius: 0" aria-current="page" href="{% url 'SOFTWARE_LIBRARY:software-library' %}">
							All
						</a>
					</li>
				{% endif %}
				{% for category in categories %}
					<li class="nav-item">
						<a class="nav-link lien" style="padding: 10px 15px;border-radius: 0" aria-current="page" href="/software-library/{{ category.category_name }}">
							{{ category }}
						</a>
					</li>
				{% endfor %}
			</ul>
			{% include 'SOFTWARE_LIBRARY/software_search_form.html' %}
		</div>
	</nav>
	{% include 'layout/pagination.html' %}
	<div class="row row-cols-1 row-cols-md-4" style="margin: 15px 10px 15px 15px;">
		{% for software in page_obj %}
			<a style="margin-bottom: 10px" href="details/{{ software.software_name }}?page={% if page_number == None %}1{% else %}{{ page_number }}{% endif %}">
				<button class="card w-100 h-100 button-software" style="background-color: #74D0F1;border:none;">
					<img class="logo-image" style="padding:0px;" width="128" height="128" src="{{ software.software_logo }}" alt="{{ software.software_name }}"/>
					<div style="margin-top:0px;">
						<h5 class="text-uppercase text-center">{{ software.software_name }}</h5>
					</div>
				</button>
			</a>
		{% endfor %}
	</div>
	{% include 'layout/pagination.html' %}
{% endblock body %}

SOFTWARE_LIBRARY/templates/SOFTWARE_LIBRARY/software_search_form.html
{% load static %}
<form class="d-flex" style="margin-bottom: 5px;margin-top: 5px" action="{% url 'SOFTWARE_LIBRARY:search' %}" method="get" accept-charset="utf-8">
	<input class="btn-outline-info form-control me-sm-2 me-md-2 me-lg-2 me-2 btn-lg" name="query" type="search" placeholder="Search" aria-label="Rechercher">
	<button class="btn btn-primary btn-lg" method="."><i class="fas fa-search"></i></button>
</form>

templates/DIAS_OMONTE/home.html
{% extends 'layout/head.html' %}
{% load static %}
{% block title %}HOME{% endblock title %}
{% block favicon %}<link rel="shortcut icon" type="image/png" href="{% static 'medias/images/photo_alexandre.png' %}">{% endblock favicon %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block body %}
	<h4>bonjour à tous !</h4>
{% endblock body %}

templates/layout/footer.html
<footer class="text-center text-white text-lg-center" style="background-color: #1E7FCB;margin-bottom: 0;width: 100%;">
	<div class="h4 p-4 fw-bold col-12" style="margin-bottom: 0">
		Alexandre Dias- -Omonte&copy; - {% now 'Y' %} - All right reserved.
	</div>
</footer>

templates/layout/head.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
	<head>
		<title>{% block title %}{% endblock title %}</title>
		{% block favicon %}<link rel="shortcut icon" type="image/png" href="{% static 'medias/images/photo_alexandre.png' %}">{% endblock favicon %}
		<meta charset="utf-8">
		<meta name="viewport" content="width = device-width, initial-scale = 1.0">
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
		<link rel="stylesheet" type="text/css" href="{% static 'files/css/styles.css' %}">
		<script src="https://kit.fontawesome.com/8b420c83a1.js" crossorigin="anonymous"></script>
	</head>
	<body class="fond" style="position: absolute;">
		{% include 'layout/menu.html' %}
		{% block breadcrumb %}
		<nav aria-label="breadcrumb" style="position:fixed;top:0px">
  			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="{% url 'home' %}"><img class="portrait" src="{% static 'medias/images/photo_alexandre.png' %}"/></a></li>
    			<li class="breadcrumb-item"><a href="{% url 'home' %}">HOME</a></li>
    			<li class="breadcrumb-item active"><a href="{% url 'RESTAURANTS:restaurants' %}">SOFTWARE LIBRARY</a></li>
  			</ol>
		</nav>
		{% endblock breadcrumb %}
		{% block body %}{% endblock body %}
		{% include 'layout/footer.html' %}
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	</body>
</html>

templates/layout/menu.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color:#74D0F1;width: 100%;">
    <a class="nav-link brand accueil" href="{% url 'home' %}"><img class="image_menu" src = "{% static 'medias/images/photo_alexandre.png' %}"/><span class="sr-only">(current)</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link brand accueil lien" href="{% url 'home' %}">HOME</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link brand lien" href="{% url 'RESTAURANTS:restaurants' %}">RESTAURANTS</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link brand lien" href="{% url 'SOFTWARE_LIBRARY:software-library' %}">SOFTWARE LIBRARY</a>
            </li>
        </ul>
    </div>
</nav>

templates/layout/pagination.html
{% load static %}
<nav aria-label="pagination">
	<ul class="pagination pagination-lg justify-content-center">
		{% if page_obj.has_previous %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
			</li>
		{% else %}
			<li class="page-item disabled">
				<a class="page-link" href="#">Previous</a>
			</li>
		{% endif %}
		{% for i in page_obj.paginator.page_range %}
      		{% if page_obj.number == i %}
        		<li class="page-item active">
					<span class="page-link">{{ i }}</span>
				</li>
      		{% else %}
        		<li class="page-item">
					<a class="page-link" href="?page={{ i }}">{{ i }}</a>
				</li>
      		{% endif %}
    	{% endfor %}
		{% if page_obj.has_next %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
			</li>
		{% else %}
			<li class="page-item disabled">
				<a class="page-link" href="#">Next</a>
			</li>
		{% endif %}
	</ul>
</nav>

templates/layout/pagination_search.html
{% load static %}
<nav aria-label="pagination">
	<ul class="pagination pagination-lg justify-content-center">
		{% if page_obj_search.has_previous %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj_search.previous_page_number }}">Previous</a>
			</li>
		{% else %}
			<li class="page-item disabled">
				<a class="page-link" href="#">Previous</a>
			</li>
		{% endif %}
		{% for i in page_obj_search.paginator.page_range %}
      		{% if page_obj_search.number == i %}
        		<li class="page-item active">
					<span class="page-link">{{ i }}</span>
				</li>
      		{% else %}
        		<li class="page-item">
					<a class="page-link" href="?page={{ i }}">{{ i }}</a>
				</li>
      		{% endif %}
    	{% endfor %}
		{% if page_obj_search.has_next %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj_search.next_page_number }}">Next</a>
			</li>
		{% else %}
			<li class="page-item disabled">
				<a class="page-link" href="#">Next</a>
			</li>
		{% endif %}
	</ul>
</nav>